AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - vendor/bundle/**/*
    - 'spec/**/*' # Exclude all files under the 'spec' directory
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
