:concurrency: 1
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - updates
  - mailers
  - active_storage_analysis
  - active_storage_purge
:scheduler:
  :schedule:
    jobs_updater:
      cron: '0 1 * * *' # Runs once per day (at 1 am)
      class: UpdateExistingCompanyJobs
      queue: updates
    devitjobs_api_pull:
      cron: '0 2 * * *' # Runs once per day (at 2 am)
      class: Scraper::DevItJob
      queue: updates
    # true_up_scraper: # off for now as we have already pulled all the ATS identifiers
    #   cron: '0 2 * * *' # Runs once per day (at 2 am)
    #   class: ScrapeTrueUpJob
    #   queue: updates
    # workable_xml_importer: # off for now as not currently working
    #   cron: '0 4 * * *' # Runs once per day (at 4 am)
    #   class: Xml::WorkableJob
    #   queue: updates
    # monster_scraper: # off for now as don't need this functionality
    #   cron: '0 5 * * *'   # Runs once per day(at midnight)
    #   class: Scraper::MonsterJob
    #   queue: updates
